# ============================================================================
# MRI Super-Resolution · BASE CONFIG
# All experiment-specific YAML files simply `parent:` this one and override
# what they need.
# ============================================================================

# ---------------------------------------------------------------------------
# 0. Runtime / device
device:
  use_cuda: true            # the notebook still picks CPU automatically if no GPU

# ---------------------------------------------------------------------------
# 1. Data
data:
  dir: "./data"             # root folder that contains train/ and val/ splits
  transforms: "./configs/transforms.yaml"
  workers: 4
  preview_batch: 1

# ---------------------------------------------------------------------------
# 2. Model (architecture-specific hyper-params live here)
model:
  name: "willnet"           # ("willnet", "willnet_se_deep", …)
  in_channels: 1
  out_channels: 1           # ↳ both optional for most nets
  mid_channels: 48          # ↳ used only by *_se* variants
  n_blocks: 8               # ↳   "

# ---------------------------------------------------------------------------
# 3. Training
train:
  batch_size: 4
  epochs: 100
  lr: 1e-4                  # keep short key **lr** (matches Trainer arg)
  gamma: 0.5                # MSE : SSIM blend
  patience: 20              # early-stop
  output_dir: "./checkpoints"

# ---------------------------------------------------------------------------
# 4. Evaluation
eval:
  batch_size: 1
  save_visual: true
  output_dir: "./results"

