# =============================================
# MRI Super-Resolution Base Configuration
# =============================================

# Data paths
data_dir: "./data"
transforms_config: "./configs/transforms.yaml"

# Hardware settings
num_workers: 4
use_cuda: true

# Model configuration
model_params:
  in_channels: 1
  out_channels: 1
  
# Training configuration
training:
  batch_size: 5
  learning_rate: 1e-3
  epochs: 10
  gamma: 0.5
  
# Validation configuration
validation:
  batch_size: 1
  
# Logging configuration
log_interval: 10