# MRI Super-Resolution Transforms Configuration

# Global transforms (apply to both train and val unless overridden)
transforms:

# Training-specific configuration
train:
  apply_transforms: true
  transforms:
    horizontal_flip:
      enabled: true
      p: 0.5
    vertical_flip:
      enabled: true
      p: 0.5
    rotate:
      enabled: true
      p: 1.0  
      mode: "fixed"    # Options: "fixed" or "range"
      fixed:
        angles: [90, 180, 270]
      range:
        limit: 30       # ± degrees
      interpolation: 1  # INTER_LINEAR
      border_mode: 4    # BORDER_REFLECT_101 
      fill_value: [0, 0, 0]  
      crop_after: false  
    gauss_noise:
      enabled: true
      var_limit: [0.0001, 0.002]
      p: 1.0

# Validation-specific configuration
val:
  apply_transforms: true
  transforms:
    # Could override from global if needed