# MRI Super-Resolution Transforms Configuration

# Global transforms (apply to both train and val unless overridden)
transforms:
  normalize:
    enabled: true
    mean: [0.5]
    std: [0.5]

# Training-specific configuration
train:
  apply_transforms: true  
  transforms:
    horizontal_flip:
      enabled: true
      p: 0.5
    vertical_flip:
      enabled: true
      p: 0.5
    rotate:
      enabled: true
      limit: 15
      p: 0.5
    elastic_transform:
      enabled: true
      alpha: 1.0
      sigma: 50.0
      alpha_affine: 50.0
      p: 0.5
    gauss_noise:
      enabled: true
      var_limit: [0.001, 0.01]
      p: 0.3

# Validation-specific configuration
val:
  apply_transforms: true
  transforms:
    # Just normalization (inherits from global)
    # Could override from global if needed